modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="COFH Don't Be A Jerk"
[[mods]] #mandatory
modId="ascensiontweaker" #mandatory
version="${file.jarVersion}" #mandatory
displayName="AscensionTweaker" #mandatory
updateJSONURL="" #optional
authors="winterSteve25" #optional
description='''
'''
[[dependencies.ascensiontweaker]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.ascensiontweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ascensiontweaker]]
    modId="aoa3"
    mandatory=true
    versionRange="[3.5.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ascensiontweaker]]
    modId="fclib"
    mandatory=true
    versionRange="[2.1.3,)"
    ordering="NONE"
    side="BOTH"